### ISSUE TITLE
Bug on frames

### ISSUE THREAD

**Issue by kasteiner** [YoungNeer/animX#1]
I am trying to use this kind of image 

http://www.rpg-maker.fr/ressources/vxchar/image[1].png

however, with this kind of initialization, i cant get the right frames to display for the first row.

How would you create switch for these front back left right animations?

`hero = animx.newAnimation{
	img='img/ninja.png',
	noOfFrames=12,
	spritesPerRow=3,
        frames={1,2,3}
	}:loop()`

**Comment by besnoi** [comment]
You are giving "too much information"!! I made an [new example](https://github.com/YoungNeer/animX/tree/master/Examples/RPG%20Animation)! You can refer to that
(and btw i used the same image you provided if that's okay with you)
